#!/bin/zsh

numRuns=5

function runGateBenchmarks(){
    make singleQBenchmark NUMQUBITS=1
    make cleanObj
    make twoQBenchmark NUMQUBITS=2
    make cleanObj
    make threeQBenchmark NUMQUBITS=3
    make cleanObj
    ./singleQGateTimes
    ./twoQGateTimes
    ./threeQGateTimes
}

function runEprBenchmark(){
    make eprBenchmark NUMQUBITS=$1
    for ((i = 0; i < numRuns; i++));
        ./epr
        make cleanObj
}

function runMain(){
    make NUMQUBITS=$1
    for ((i = 0; i < numRuns; i++));
        ./main
    make cleanObj
}

if [ "$1" = "gateBenchmarks" ]; then
        runGateBenchmarks
elif [ "$1" = "eprBenchmark" ]; then
    runEprBenchmark $2
else
    runMain $1
fi