name: QuantumSim CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build-ubuntu:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make check
      run: make check
    - name: make
      run: make

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: make check
      run: make check
    - name: make
      run: make
