name: QuantumSim CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make check
      run: make check
    - name: make
      run: make

  build-macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: install libomp
      run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" \
        brew install libomp \
    - name: make check
      run: make check
    - name: make
      run: make
